apiVersion: v1
kind: Service
metadata:
  name: csp-chunker
  labels:
    app: csp-chunker
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: external
  selector:
    app: csp-chunker