apiVersion: apps/v1
kind: Deployment
metadata:
  name: csp-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csp-scraper
  template:
    metadata:
      labels:
        app: csp-scraper
    spec:
      containers:
        - name: csp-scraper
          image: 'tenaacr.azurecr.io/csp-scraper:443ff147254c136546a29cce499b48b494819940' 
          ports:
            - containerPort: 8060
          resources:
            limits:
              memory: 1280Mi
            requests:
              memory: 500Mi
              cpu: "0.5"
          livenessProbe:
            httpGet:
              path: '/healthz'
              port: 8060
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 50
          readinessProbe:
            httpGet:
              path: '/healthz'
              port: 8060
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 50
