apiVersion: v1
kind: Service
metadata:
  name: csp-scraper
  labels:
    app: csp-scraper
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8060
      name: external
  selector:
    app: csp-scraper