apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity
spec:
  provider: azure
  secretObjects:
    - data:
        - key: Weaviate__ApiKey
          objectName: Weaviate__ApiKey
        - key: OpenAi__ApiKey
          objectName: OpenAi__ApiKey
        - key: ConnectionStrings__DefaultConnection
          objectName: ConnectionStrings__DefaultConnection
        - key: Finbuckle__MultiTenant__Stores__ConfigurationStore__Defaults__ConnectionString
          objectName: Finbuckle__MultiTenant__Stores__ConfigurationStore__Defaults__ConnectionString
      secretName: appkvsecrets
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "5843cb30-0f68-441b-a7de-7dd7d73c107d" # workload identity id
    keyvaultName: antcs-test-kv
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    #objectName is the name of the secret in the key vault
    #objectAlias is what we map to
    objects:  |
      array:
        - |
          objectName: 'weaviate-api-key'
          objectAlias: Weaviate__ApiKey
          objectType: secret
        - |
          objectName: 'openai-api-key'
          objectAlias: OpenAi__ApiKey
          objectType: secret
        - |
          objectName: 'database-connection-string'
          objectAlias: ConnectionStrings__DefaultConnection
          objectType: secret
        - |
          objectName: 'database-connection-string'
          objectAlias: Finbuckle__MultiTenant__Stores__ConfigurationStore__Defaults__ConnectionString
          objectType: secret
    tenantId: "8d6a5992-5ef6-42bc-b8b0-535c398128c2"
